= Testy A Design Aplikacji

== Zacznijmy od testu! [01]

=== Kod [09-01-tdd]

Pythonowy odpowiednik kodu ze slajdu [Brak przyjemności z testowania] znajdziemy w
`05-architecture/05-02-packages/05-02-01-core/tests/lesson1/_01_bad_class_tests.py` - `Test01BadClass.test_heavy_monkey_patching`.

Najpierw kodujemy w `tests/verifier/tdd/_01_acceptance_tests.py`. Na slajdach będziemy przechodzić linia po linii włącznie z kodem, który nie może zostać jeszcze zinterpretowany przez Pythona.

Następnie kod, gdzie tworzymy widok, który nic nie robi jest dostępny w pliku `_02_acceptance_view_tests.py`. W tym momencie tworzymy prostą implementację widoku, który zwraca `None`.

Potem w `_03_acceptance_view_something_tests.py` tworzymy klasę `Something`, która jeszcze nie do końca wiemy, co będzie robiła.

Po tym, jak rozpiszemy sobie co mamy zrobić z naszym klientem, dochodzimy do wniosku, że chcemy zweryfikować oszusta. Zatem tworzymy klasę `FraudVerifier` w pliku `_04_fraud_verifier_failing_tests.py`, która jeszcze nie ma implementacji.

W `_05_fraud_verifier_tests.py` zapisujemy przypadki testowe dla naszej implementacji weryfikacji oszusta. Najpierw chcemy żeby jeden test przeszedł, a potem drugi.

W końcu możemy puścić zestaw testów akceptacyjnych `_06_acceptance_tests.py`, które teraz przechodzą.

== Piramida testów [02]

=== Kod [09-02-pyramid]

Kod do slajdu dot. tego, czy piramida testów jest zawsze taka sama `pyramid_tests.py`. Pokazujemy tu symulacje widoku, który przekazuje wywołania do klasy łączącej się z bazą danych.

== Przykłady złych testów [03]

* Mockowanie typów wbudowanych. `09-03-bad-tests` zawiera plik `bad_tests.py` zawiera klasę `_03_FraudService`, gdzie korzystamy "na sztywno" z innej klasy - `Dao`. W teście `test_should_find_any_empty_name` mockujemy wszystko co się dai w dodatku stosujemy monkey-patching tak że całkowicie odseparowujemy klasę `_03_Fraud_Service`.
* Mockowanie typów wbudowanych c.d. -  ten sam plik, tym razem test `test_should_find_any_empty_name_fixed`. Wiemy już, że monkey-patching na dłuższą metę jest szkodliwy. Tutaj pokazujemy jak przygotować nasze klasy na wstrzykiwanie zależności i że upraszcza to test.
* Brak asercji - Klasa `Test01NoAssertions` i zawsze przechodzący test. Pokazujemy problem pominięcia asercji skutkujący zawsze przechodzącymi testami (nawet jeśli testowana implementacja jest błędna).
* Za dużo mocków - Klasa `Test02DoesUnittestMockWork` i operowanie tylko na mockach. De facto nie testujemy nic, poza tym, że framework do mockowania działa.
* Stanowość - plik `_04_potential_fraud_service_tests.py` pokazuje problemy związane ze stanowością w testach.
* Testy niewykrywalne przez pytest poprzez nietrzymanie się ustawionej konwencji nazewniczych plików, klas i funkcji/metod testowych `09-03-discovery-problemts`. Warto odnotować, że pytest zwróci kod błędu 5, jeśli nie znajdzie żadnego testu.

== Praca z zastanym kodem

=== Kod [09-04-legacy]

Klasa `_01_FraudVerifier` z pliku `_01_fraud_verifier.py` widoczna na slajdzie po [Cel pracy ze źle zaprojektowanym kodem].

W pliku `_02_fraud_verifier_tests.py` mamy klasę `_03_DatabaseAccessorImpl`. Na jej podstawie powstał kod na slajdzie po screenshocie 4 000 linii kodu.

Następnie próba napisania testu `test_marks_client_with_debt_as_fraud`.

Czas na szew (seam) - `_04_FakeDatabaseAccessor`. Nadpisujemy problematyczną metodę bez zmiany kodu produkcyjnego i test `test_marks_client_with_debt_as_fraud_with_seam`.

Teraz chcemy dodać nową funkcję systemu do klasy `_05_FraudTaxPenaltyCalculator`.

Pierwsze podejście z `if/else` w `_06_FraudTaxPenaltyCalculatorIfElse`. Problem w tym, że dodajemy nowy kod do nieprzetestowanego.

Wprowadzamy pojęcie Klasy Kiełkowania (Sprout). Czyli za pomocą TDD piszemy nową, przetestowaną klasę, który wywołamy w naszym kodzie legacy (`_07_FraudTaxPenaltyCalculatorSprout`). Process TDD widoczny tu `_08_special_tax_calculator_tax_test.py`.

Załóżmy, że mamy klasę, która wylicza czy dana osoba jest oszustem lub nie, w zależności od tego, czy posiada dług. By wyciągnąć te informacje, musimy odpytać bazę danych. Akcesor do bazy danych tworzony jest w konstruktorze. Załóżmy, że mamy taką implementację weryfikatora oszustów `_09_FraudVerifierLogicInConstructor` i taką dostępu do bazy danych `_10_DatabaseAccessorImplWithLogicInTheConstructor`. Pierwszą rzeczą, którą możemy zrobić to spróbować w ogóle utworzyć nasz obiekt. Napiszmy test `Test02FraudVerifier.test_creates_an_instance_of_fraud_verifier`. Test wybuchnie! Co możemy zrobić?

W `_11_FraudVerifierLogicInConstructorExtractLogic` widzimy, że możemy dodać dodatkowy, domyślny argument initializera, żeby nie tworzyć problematycznego obiektu w środku, tylko opcjonalnie przekazać już utworzony wcześniej obiekt do initializera. Teraz, możemy utworzyc mocka problematycznego obiektu i napisać test `Test02FraudVerifier.test_marks_client_with_debt_as_fraud_with_a_mock`.

Teraz możemy wprowadzić nową klasę abstrakcyjną `_12_DatabaseAccessor`,  który pokrywa się z już istniejącym kodem. Podmieniamy w initializerze `FraudVerifier`a klasę konkretną na abstrakcyjną (`_13_FraudVerifierWithInterface`). Dzięki temu możemy też stworzyć implementację test-double na potrzeby testu `_14_FakeDatabaseAccessorWithInterface`.

Poprzez taką operację jesteśmy w stanie bardzo uprościć nasz test `Test02FraudVerifier.test_marks_client_with_debt_as_fraud_with_an_extracted_interface`.

==== Obiektu nie da się łatwo utworzyć

Plik `_015_fraud_verifier_tests.py`. Zawiera implementację `_16_FraudVerifier` jako przykład implementacji z wieloma zależnościami i dużą liczbą linijek kodu.

Pokazujemy dwa przykłady testów, w których próbujemy odgadnąć, które zależności są wymagane poprzez podstawienie None'a. `Test15FraudVerifier.test_should_calculate_penalty_when_fraud_applies_for_a_loan` nie trafiamy i leci `AttributeError`. W `Test15FraudVerifier.test_should_mark_client_with_debt_as_fraud` trafiamy i test nam przechodzi. W teście `Test15FraudVerifier.test_should_calculate_penalty_when_fraud_applies_for_a_loan_with_both_deps` przekazujemy brakującą zależność i test przechodzi.

==== Globalne zależności

Plik `_17_fraud_verifier_tests.py`. W klasie `_18_FraudVerifier` mamy przykład implementacji wołającej obiekt utworzony w innym module w miejscu i stamtąd zaimportowany - instancję `_19_DatabaseAccessor`.

Ta sytuacja jest tą ostateczną, w której monkey-patching (`unittest.mock.patch`) nie jest najgorszym pomysłem. Za pomocą tej techniki podmieniamy na czas wywołania metody instancję w innym module. Żeby zachować resztki pozorów, użyjemy klasy dziedziczącej po tej kłopotliwej - `_21_FakeDatabaseAccessor`. Można by też użyć w tym miejscu Mocka (koniecznie ze `spec_set=_19_DatabaseAccessor`!).

Dzięki używaniu context managera (słowo kluczowe `with`) z `patch` upewniamy się, że posprzątamy po sobie. Skorzystanie z innego API i ręczne patchowanie jest niezalecane ze względu na ryzyko niewyczyszczenia stanu (o ile programista zapomni, rzecz jasna) i powstanie bardzo trudnych do wyśledzenia błędów.
