global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: fraud_verifier_metrics
    static_configs:
      - targets: ['fraud_verifier:9090']
  - job_name: loan_orders_metrics
    static_configs:
      - targets: ['loan_orders:9091']