version: '3'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: smarttesting
      POSTGRES_USER: smarttesting
      POSTGRES_PASSWORD: smarttesting
    ports:
    - 5432:5432
  rabbitmq:
    image: rabbitmq:3.9.7-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: smarttesting
      RABBITMQ_DEFAULT_PASS: smarttesting
    ports:
    - 5672:5672
    - 15672:15672
  app:
    build: ./
    environment:
      APP_ENV: "DEV"
      DB_URL: "postgresql://smarttesting:smarttesting@postgres:5432/smarttesting"
      BROKER_URL: "amqp://smarttesting:smarttesting@rabbitmq:5672/"
    ports:
    - 8000:8000
    depends_on:
      - rabbitmq
      - postgres
